# Note: this environment will be merged with the pangeo-notebook/environment.yml
# by conda-lock. Only put things here that are not already in pangeo-notebook
name: pangeo
channels:
 - conda-forge
dependencies:
 - tensorflow==2.8.1=*cuda*
