name: pangeo
channels:
  - conda-forge
  - pangeo
dependencies:
  - python=3.7
  - pangeo-notebook=0.0.2
  # Additional libraries
  - cartopy
  - dask-ml
  - datashader
  - fsspec
  - gcsfs
  - geopandas
  - geoviews-core
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-esm=2019
  - intake-stac
  - intake-xarray
  - ipyleaflet
  - jupyter-panel-proxy
  - lz4
  - matplotlib-base
  - numpy
  - pandas
  - panel
  - rasterio
  - s3fs
  - sat-search
  - sat-stac
  - satpy
  - scikit-image
  - scikit-learn
  - scipy
  - xarray
  - zarr
