name: pangeo
channels:
 - conda-forge
dependencies:
 - python=3.7*
 - pangeo-notebook=2020.05.10
 - pip=20
 - awscli
 - cartopy
 - dask-ml
 - datashader
 - descartes
 - fsspec
 - gcsfs
 - geopandas
 - geoviews-core
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipywidgets
 - ipyleaflet
 - jq
 - jupyter-panel-proxy
 - lz4
 - matplotlib-base
 - metpy
 - nomkl
 - numpy
 - numcodecs
 - pandas
 - panel
 - prefect
 - pydap
 - python-blosc
 - rasterio
 - rio-cogeo
 - s3fs
 - sat-search
 - sat-stac
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - sparse
 - tiledb-py
 - xarray
 - xesmf
 - xpublish
 - zarr
