name: pangeo
channels:
 - conda-forge
dependencies:
 - python=3.7*
 - pangeo-notebook=2020.06.19
 - pip=20
 - bottleneck
 - cartopy
 - ciso
 - dask-ml
 - datashader
 - descartes
 - fastjmd95
 - fsspec
 - gcsfs
 - geopandas
 - geoviews-core
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipyleaflet
 - ipywidgets
 - jupyter-panel-proxy
 - lz4
 - matplotlib-base
 - metpy
 - nc-time-axis
 - netcdf4
 - nomkl
 - numcodecs
 - numpy
 - pandas
 - panel
 - prefect
 - pyarrow
 - pydap
 - python-blosc
 - rasterio
 - rio-cogeo
 - s3fs
 - sat-search
 - sat-stac
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - sparse
 - tiledb-py
 - xarray
 - xcape
 - xesmf
 - xgcm
 - xhistogram
 - xlayers
 - xmitgcm
 - xpublish
 - xrft
 - zarr
