name: pangeo
channels:
 - conda-forge
 - nodefaults
dependencies:
 - adlfs
 # https://github.com/euroargodev/argopy/issues/390
 - argopy<0.1.16
 - awscli
 - black
 - boto3
 - bottleneck
 - cartopy
 - cdsapi
 - cfgrib
 - cf_xarray
 - ciso
 - cmocean
 - contextily
 - dask-geopandas
 - dask-ml
 - datashader
 - descartes
 - duckdb-cli
 - earthaccess
 - eofs
 - erddapy
 - esmpy
 - fastjmd95
 - flox
 - fsspec
 - gcm_filters
 - gcsfs
 - gdal
 - gh
 - gh-scoped-creds
 - geocube
 - geopandas
 - geopy
 - geoviews-core
 - git-lfs
 - gsw
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipdb
 - ipykernel
 - ipyleaflet
 - ipympl
 - ipytree
 - ipywidgets
 - jupyterlab_code_formatter
 - jupyterlab-git
 - jupyterlab-lsp
 - jupyterlab-myst
 - jupyter-panel-proxy
 - jupyter-resource-usage
 - jupyter-sshd-proxy
 - kerchunk
 - line_profiler
 - lonboard
 - lxml
 - lz4
 - matplotlib-base
 - memory_profiler
 - metpy
 - nb_conda_kernels
 - nbstripout
 - nc-time-axis
 - netcdf4
 - numbagg
 - numcodecs
 - numpy
 - numpy_groupies
 - odc-stac
 - openssh
 - pandas
 - panel
 # https://github.com/OceanParcels/Parcels/issues/1819
 #- parcels
 - param
 - planetary-computer
 - pop-tools
 - pyarrow
 - pycamhd
 - pydap
 - pystac
 - pystac-client
 - python-blosc
 - python-duckdb
 - python-gist
 - python-graphviz
 - python-lsp-ruff
 - python-xxhash
 - rasterio
 - rechunker
 - rio-cogeo
 - rioxarray
 - ruff
 - s3fs
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - sparse
 - snakeviz
 - stackstac
 - tiledb-py
 - timezonefinder
 - watermark
 - xarray
 - xarrayutils
 - xarray_leaflet
 - xarray-spatial
 - xbatcher
 # https://github.com/conda-forge/xcape-feedstock/pull/22
 #- xcape
 - xclim
 - xesmf
 - xgboost
 - xgcm
 - xhistogram
 - xmip
 - xmitgcm
 - xpublish
 - xrft
 - xskillscore
 - xxhash
 - xvec
 - zarr
