# Note: this environment will be merged with the pangeo-notebook/environment.yml
# by conda-lock. Only put things here that are not already in pangeo-notebook
name: pangeo
channels:
 - conda-forge
 - nodefaults
dependencies:
 - cuda-version>=12.0
 - jupyterlab-nvdashboard
 - gpytorch
 - pytorch>=2.1.0=cuda120*
 - tensorboard
 - tensorflow
 - torchvision>=0.16.1=cuda120*
 - torchgeo
