# Add Binder Link to PR for testing pangeo-notebook image
name: BinderPR

on:
  pull_request_target:
    types: [opened]

permissions: {}

jobs:
  add-binder-links:
    runs-on: ubuntu-latest
    steps:
    - name: Add BinderHub Links
      uses: peter-evans/create-or-update-comment@v4
      env:
        PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        PR_HEAD_USERREPO: ${{ github.event.pull_request.head.repo.full_name }}
      with:
         token: ${{ secrets.GITHUB_TOKEN }}
         issue-number: ${{github.event.number}}
         reactions: rocket
         body: |
          [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/${{env.PR_HEAD_USERREPO}}/${{env.PR_HEAD_REF}}) :point_left: Try on Mybinder.org!
