# Any commit to master branch re-builds images, re-runs tests, and pushes SHA tags to DockerHub
name: Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'Makefile'
      - 'environment-condalock.yml'
      - 'update_lockfile.sh'

env:
  DOCKER_ORG: pangeo
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  base-image:
    env:
      IMAGE: base-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Job Environment Variables
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        IMAGE_SPEC="${DOCKER_ORG}/${{ env.IMAGE }}:${DOCKER_TAG}"
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
        echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV

    - name: Build and Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: ${{env.DOCKER_ORG}}/${{ env.IMAGE }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        workdir: ${{ env.IMAGE }}
        tags: "master, ${{env.DOCKER_TAG}}"


  matrix-build:
    needs: base-image
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [base-notebook, pangeo-notebook, ml-notebook]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Job Environment Variables
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        IMAGE_SPEC="${DOCKER_ORG}/${{ matrix.IMAGE }}:${DOCKER_TAG}"
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
        echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV

    - name: Build and Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: ${{env.DOCKER_ORG}}/${{ matrix.IMAGE }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        workdir: ${{ matrix.IMAGE }}
        tags: "master, ${{env.DOCKER_TAG}}"

    - name: Export Full Conda Environment
      run: |
        docker run ${DOCKER_ORG}/${{ matrix.IMAGE }}:master conda list --export

    - name: Test Image
      run: |
        docker run -u 1000 -w /srv/test -v $PWD:/srv/test ${DOCKER_ORG}/${{ matrix.IMAGE }}:master ./run_tests.sh ${{ matrix.IMAGE }}
