# Any commit to master branch re-builds images, re-runs tests, and pushes SHA tags to DockerHub
name: Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'Makefile'
      - 'environment-condalock.yml'
      - 'update_lockfile.sh'

env:
  DOCKER_ORG: cnes
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  base-image:
    env:
      IMAGE: base-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Job Environment Variables
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ env.IMAGE }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{env.DOCKER_ORG}}/${{ env.IMAGE }}:master
          ${{env.DOCKER_ORG}}/${{ env.IMAGE }}:${{env.DOCKER_TAG}}

  matrix-build:
    needs: base-image
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [base-notebook, pangeo-notebook, pytorch-notebook]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Job Environment Variables
      run: |
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

    # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
    - name: Free up disk space
      run: |
        df -h
        docker image ls
        sudo apt clean
        sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
        df -h

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.IMAGE }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{env.DOCKER_ORG}}/${{ matrix.IMAGE }}:master
          ${{env.DOCKER_ORG}}/${{ matrix.IMAGE }}:${{env.DOCKER_TAG}}

    - name: Inspect Image
      run: |
        docker run ${DOCKER_ORG}/${{ matrix.IMAGE }}:master conda list
        docker images ls

    - name: Test Image
      run: |
        docker run -u 1000 -w /srv/test -v $PWD:/srv/test ${DOCKER_ORG}/${{ matrix.IMAGE }}:master ./run_tests.sh ${{ matrix.IMAGE }}
