# Respond to every Pull Request with Pangeo Bot!
name: PullRequest

on:
  pull_request_target:
    types: [opened, reopened]
    paths: ["**/environment.yml"]

permissions: {}

jobs:
  DeployPangeoBot:
    runs-on: ubuntu-latest
    if: github.repository == 'pangeo-data/pangeo-docker-images'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Add Condalock Comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          token: ${{ secrets.PANGEOBOT_TOKEN }}
          issue-number: ${{github.event.number}}
          body: |
            /condalock
            Automatically locking new conda environment, building, and testing images...
