# Only test building image
name: PullRequest

on:
  pull_request:
    branches:
      - master

env:
  DOCKER_ORG: ${DOCKER_ORG}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [base-image, pangeo-image, ml-image]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Sync base-config files without overwriting
      run: |
        rsync -a -v --ignore-existing base-image/* ${{ matrix.IMAGE }}/

    - name: Build Image
      run: |
        cd ${{ matrix.IMAGE }}
        docker build -t ${DOCKER_ORG}/${{ matrix.IMAGE }}:PR .

    - name: Export Full Conda Environment
      run: |
        docker run ${DOCKER_ORG}/${{ matrix.IMAGE }}:PR conda env export

    - name: Test Image
      run: |
        docker run -u root -v $PWD:/home/jovyan ${DOCKER_ORG}/${{ matrix.IMAGE }}:PR ./run_tests.sh
