name: Staging
on:
  push:
    branches:
      - master
# https://github.com/elgohr/Publish-Docker-Github-Action#cache
#  schedule:
#    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

env:
  DOCKER_ORG: pangeodev
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [base-image, pangeo-image, ml-image]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Job Environment Variables
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        IMAGE_SPEC="${DOCKER_ORG}/${{ matrix.IMAGE }}:${DOCKER_TAG}"
        echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
        echo "::set-env name=IMAGE_SPEC::${IMAGE_SPEC}"

    - name: Sync Base-config Files
      run: |
        rsync -a -v --ignore-existing base-image/* ${{ matrix.IMAGE }}/

    - name: Build and Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: ${{env.DOCKER_ORG}}/${{ matrix.IMAGE }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        workdir: ${{ matrix.IMAGE }}
        tags: "master, ${{env.DOCKER_TAG}}"
#        cache: ${{ github.event_name != 'schedule' }}
    # NOTE: could save this as a build artifact or put on website
    - name: Export Full Conda Environment
      run: |
        docker run ${DOCKER_ORG}/${{ matrix.IMAGE }}:master conda env export

    - name: Test Image
      run: |
        docker run -u root -v $PWD:/home/jovyan ${DOCKER_ORG}/${{ matrix.IMAGE }}:master ./run_tests.sh
